In [ ]:
#计算两点之间的距离

In [38]:
import numpy as np

In [126]:
# 初始化点
#middle_point
center_atom=np.array([-0.000013145,2.470234785,1.760399198])
#Cr_atom order R-18, L-18, U-19, B-19, -20, B-20

cr_atom= np.array([[4.27855153,2.470234785,1.760399198],
[-4.27858,2.47023,1.7604],
[-2.139300178,6.175578363,1.760399198],
[2.13927,-1.23511,1.7604],
[2.139264497,6.175578363,1.760399198],
[-2.13929,-1.23511,1.7604]])
sum_p=(cr_atom[0]+center_atom,
              cr_atom[1]+center_atom,
              cr_atom[2]+center_atom,
              cr_atom[3]+center_atom,
              cr_atom[4]+center_atom,
              cr_atom[5]+center_atom)
middle_p=np.array(sum_p)/2
print('middle_p')
print(middle_p)

up_point=np.array([[2.139262102,3.70535255,3.128645021],
[-2.13929,3.70535,3.12865],
[-2.13929,3.70535,3.12865],
[0,0,3.12865],
[2.139262102,3.70535255,3.128645021],
[0,0,3.12865]])

dn_point=np.array([[2.139276257,1.235117109,0.353022121],
[-2.13929,1.23512,0.35302],
[-0.000010585,4.940460356,0.353022121],
[2.139276257,1.235117109,0.353022121],
[-0.000010585,4.940460356,0.353022121],
[-2.13929,1.23512,0.35302]])


middle_p
[[ 2.13926919  2.47023479  1.7603992 ]
 [-2.13929657  2.47023239  1.7603996 ]
 [-1.06965666  4.32290657  1.7603992 ]
 [ 1.06962843  0.61756239  1.7603996 ]
 [ 1.06962568  4.32290657  1.7603992 ]
 [-1.06965157  0.61756239  1.7603996 ]]
R178 [2.13926919 2.47023479 1.7603992 ]


In [128]:
point_MR178 = middle_p[0]
#MR178_Te10_up
#MR178_Te3_dn
point_Te10 = up_point[0]
point_Te3 = dn_point[0]
point_ML178 = middle_p[1]
#ML178_Te7_up
#ML178_Te6_dn
point_Te7 = up_point[1]
point_Te6 = dn_point[1]
point_MU179 =middle_p[2]
#MU179_Te7_up
#MU179_Te9_dn
point_Te9 = dn_point[2]
point_MB179 =middle_p[3]
#MB179_Te1_up
#MB179_Te3_dn
point_Te1 = up_point[3]
point_MU170 =middle_p[4]
#MU170_Te10_up
#MU170_Te9_dn
point_MB170 =middle_p[5]
#MB170_Te1_up
#MB170_Te6_dn
n=np.sqrt(np.sum(np.square(point_MR178 - point_Te10)))
print(n)
print('point_MR178',point_MR178)
print('point_ML178',point_ML178)
print('point_MU179',point_MU179)
print('point_MB179',point_MB179)
print('point_MU170',point_MU170)
print('point_MB170',point_MB170)

1.843261382882476
point_MR178 [2.13926919 2.47023479 1.7603992 ]
point_ML178 [-2.13929657  2.47023239  1.7603996 ]
point_MU179 [-1.06965666  4.32290657  1.7603992 ]
point_MB179 [1.06962843 0.61756239 1.7603996 ]
point_MU170 [1.06962568 4.32290657 1.7603992 ]
point_MB170 [-1.06965157  0.61756239  1.7603996 ]


In [72]:
d_MR178_Te10_up = np.linalg.norm(point_MR178-point_Te10)
d_MR178_Te3_dn = np.linalg.norm(point_MR178-point_Te3)
d_ML178_Te7_up = np.linalg.norm(point_ML178-point_Te7)
d_ML178_Te6_dn = np.linalg.norm(point_ML178-point_Te6)
d_MU179_Te7_up = np.linalg.norm(point_MU179-point_Te7)
d_MU179_Te9_dn = np.linalg.norm(point_MU179-point_Te9)

d_MB179_Te1_up = np.linalg.norm(point_MB179-point_Te1)
d_MB179_Te3_dn = np.linalg.norm(point_MB179-point_Te3)

d_MU170_Te10_up = np.linalg.norm(point_MU170-point_Te10)
d_MU170_Te9_dn = np.linalg.norm(point_MU170-point_Te9)

d_MB170_Te1_up = np.linalg.norm(point_MB170-point_Te1)
d_MB170_Te6_dn = np.linalg.norm(point_MB170-point_Te6)
print('d_MR178_Te10_up=',d_MR178_Te10_up)
print('d_MR178_Te3_dn=',d_MR178_Te3_dn)
print('d_ML178_Te7_up=',d_ML178_Te7_up)
print('d_ML178_Te6_dn=',d_ML178_Te6_dn)
print('d_MU179_Te7_up=',d_MU179_Te7_up)
print('d_MU179_Te9_dn=',d_MU179_Te9_dn)
print('d_MB179_Te1_up=',d_MB179_Te1_up)
print('d_MB179_Te3_dn=',d_MB179_Te3_dn)
print('d_MU170_Te10_up=',d_MU170_Te10_up)
print('d_MU170_Te9_dn=',d_MU170_Te9_dn)
print('d_MB170_Te1_up=',d_MB170_Te1_up)
print('d_MB170_Te6_dn=',d_MB170_Te6_dn)

d_MR178_Te10_up= 1.843261382882476
d_MR178_Te3_dn= 1.8724918986427184
d_ML178_Te7_up= 1.8432646755787363
d_ML178_Te6_dn= 1.872490309142259
d_MU179_Te7_up= 1.8432584892236128
d_MU179_Te9_dn= 1.8724918262837387
d_MB179_Te1_up= 1.8432572911514844
d_MB179_Te3_dn= 1.872493437266763
d_MU170_Te10_up= 1.8432557306411919
d_MU170_Te9_dn= 1.8724862192746914
d_MB170_Te1_up= 1.8432707221183513
d_MB170_Te6_dn= 1.8724906140878776


In [96]:
#计算法向量 
#vector-up 
u_vec=(up_point[0]-middle_p[0],
           up_point[1]-middle_p[1],
           up_point[2]-middle_p[2],
           up_point[3]-middle_p[3],
           up_point[4]-middle_p[4],
           up_point[5]-middle_p[5])
up_vector=np.array(u_vec)

print('up_vector:')
print(up_vector)

v_R8Te10_up=up_vector[0]
v_L8Te7_up=up_vector[1]
v_U9Te7_up=up_vector[2]
v_B9Te1_up=up_vector[3]
v_U0Te10_up=up_vector[4]
v_B0Te1_up=up_vector[5]



up_vector:
[[-7.09050000e-06  1.23511777e+00  1.36824582e+00]
 [ 6.57250000e-06  1.23511761e+00  1.36825040e+00]
 [-1.06963334e+00 -6.17556574e-01  1.36825080e+00]
 [-1.06962843e+00 -6.17562393e-01  1.36825040e+00]
 [ 1.06963643e+00 -6.17554024e-01  1.36824582e+00]
 [ 1.06965157e+00 -6.17562393e-01  1.36825040e+00]]


In [97]:
#dn-vector
d_vec=(dn_point[0]-middle_p[0],
           dn_point[1]-middle_p[1],
           dn_point[2]-middle_p[2],
           dn_point[3]-middle_p[3],
           dn_point[4]-middle_p[4],
           dn_point[5]-middle_p[5])
dn_vector=np.array(d_vec)
print('dn_vector:')
print(dn_vector)

v_R8Te3_dn=dn_vector[0]
v_L8Te6_dn=dn_vector[1]
v_U9Te9_dn=dn_vector[2]
v_B9Te3_dn=dn_vector[3]
v_U0Te9_dn=dn_vector[4]
v_B0Te6_dn=dn_vector[5]


dn_vector:
[[ 7.06450000e-06 -1.23511768e+00 -1.40737708e+00]
 [ 6.57250000e-06 -1.23511239e+00 -1.40737960e+00]
 [ 1.06964608e+00  6.17553782e-01 -1.40737708e+00]
 [ 1.06964783e+00  6.17554716e-01 -1.40737748e+00]
 [-1.06963626e+00  6.17553782e-01 -1.40737708e+00]
 [-1.06963843e+00  6.17557607e-01 -1.40737960e+00]]


In [98]:
#vector-middle
m_vector=(center_atom-middle_p[0],
               center_atom-middle_p[1],
               center_atom-middle_p[2],
               center_atom-middle_p[3],
               center_atom-middle_p[4],
               center_atom-middle_p[5])
middle_vector=np.array(m_vector)
print('middle_vector:')
print(middle_vector)
 
v_R78=middle_vector[0]
v_L78=middle_vector[1]
v_U97=middle_vector[2]
v_B97=middle_vector[3]
v_U07=middle_vector[4]
v_B07=middle_vector[5]

middle_vector:
[[-2.13928234e+00  0.00000000e+00  0.00000000e+00]
 [ 2.13928343e+00  2.39250000e-06 -4.01000000e-07]
 [ 1.06964352e+00 -1.85267179e+00  0.00000000e+00]
 [-1.06964157e+00  1.85267239e+00 -4.01000000e-07]
 [-1.06963882e+00 -1.85267179e+00  0.00000000e+00]
 [ 1.06963843e+00  1.85267239e+00 -4.01000000e-07]]


In [115]:
n_R8_UP=np.cross(v_R8Te10_up,v_R78)
n_R8_DN=np.cross(v_R78,v_R8Te3_dn)

m_n_R8_UP=np.linalg.norm(n_R8_UP)
m_n_R8_DN=np.linalg.norm(n_R8_DN)

n_R8_DN_2=np.cross(v_R8Te3_dn,v_R78)
m_n_R8_DN_2=np.linalg.norm(n_R8_DN_2)

print('n_R8_UP:',n_R8_UP,m_n_R8_UP)
print('n_R8_DN:',n_R8_DN,m_n_R8_DN)
print('n_R8_DN_2:',n_R8_DN_2,m_n_R8_DN_2)

n_R8_UP: [ 0.         -2.92706412  2.64226562] 3.943256519767132
n_R8_DN: [ 0.         -3.01077692  2.64226543] 4.005788845849699
n_R8_DN_2: [ 0.          3.01077692 -2.64226543] 4.005788845849699


In [116]:
n_L8_UP=np.cross(v_L8Te7_up,v_L78)
n_L8_DN=np.cross(v_L78, v_L8Te6_dn)

m_n_L8_UP=np.linalg.norm(n_L8_UP)
m_n_L8_DN=np.linalg.norm(n_L8_DN)

n_L8_DN_2=np.cross(v_L8Te6_dn,v_L78)
m_n_L8_DN_2=np.linalg.norm(n_L8_DN_2)

print('n_L8_UP:',n_L8_UP,m_n_L8_UP)
print('n_L8_DN:',n_L8_DN,m_n_L8_DN)
print('n_L8_DN_2:',n_L8_DN_2,m_n_L8_DN_2)

n_L8_UP: [-3.76882125e-06  2.92707541e+00 -2.64226663e+00] 3.943265572929907
n_L8_DN: [-3.86243576e-06  3.01078385e+00 -2.64225547e+00] 4.005787486487962
n_L8_DN_2: [ 3.86243576e-06 -3.01078385e+00  2.64225547e+00] 4.005787486487962


In [119]:
n_U9_UP=np.cross(v_U9Te7_up,v_U97)
n_U9_DN=np.cross(v_U97,v_U9Te9_dn)

m_n_U9_UP=np.linalg.norm(n_U9_UP)
m_n_U9_DN=np.linalg.norm(n_U9_DN)

n_U9_DN_2=np.cross(v_U9Te9_dn,v_U97)
m_n_U9_DN_2=np.linalg.norm(n_U9_DN_2)

print('n_U9_UP:',n_U9_UP,m_n_U9_UP)
print('n_U9_DN:',n_U9_DN,m_n_U9_DN)
print('n_U9_DN_2:',n_U9_DN_2,m_n_U9_DN_2)

n_U9_UP: [2.53491966 1.4635406  2.6422449 ] 3.943250799288788
n_U9_DN: [2.60740781 1.50539177 2.64226551] 4.005789168350581
n_U9_DN_2: [-2.60740781 -1.50539177 -2.64226551] 4.005789168350581


In [129]:
n_B9_UP=np.cross(v_B9Te1_up,v_B97)
n_B9_DN=np.cross(v_B97,v_B9Te3_dn)

m_n_B9_UP=np.linalg.norm(n_B9_UP)
m_n_B9_DN=np.linalg.norm(n_B9_DN)

n_B9_DN_2=np.cross(v_B9Te3_dn,v_B97)
m_n_B9_DN_2=np.linalg.norm(n_B9_DN_2)

print('n_B9_UP:',n_B9_UP,m_n_B9_UP)
print('n_B9_DN:',n_B9_DN,m_n_B9_DN)
print('n_B9_DN_2:',n_B9_DN_2,m_n_B9_DN_2)

n_B9_UP: [-2.5349195  -1.46353794 -2.64224147] 3.94324740793514
n_B9_DN: [-2.60740915 -1.50538989 -2.6422692 ] 4.005791773294165
n_B9_DN_2: [2.60740915 1.50538989 2.6422692 ] 4.005791773294165


In [122]:
n_U07_UP=np.cross(v_U0Te10_up,v_U07)
n_U07_DN=np.cross(v_U07,v_U0Te9_dn)

m_n_U07_UP=np.linalg.norm(n_U07_UP)
m_n_U07_DN=np.linalg.norm(n_U07_DN)

n_U07_DN_2=np.cross(v_U0Te9_dn,v_U07)
m_n_U07_DN_2=np.linalg.norm(n_U07_DN_2)

print('n_U07_UP:',n_U07_UP,m_n_U07_UP)
print('n_U07_DN:',n_U07_DN,m_n_U07_DN)
print('n_U07_DN_2:',n_U07_DN_2,m_n_U07_DN_2)

n_U07_UP: [ 2.53491044 -1.46352885 -2.64224499] 3.943240570397287
n_U07_DN: [ 2.60740781 -1.50538516 -2.64224442] 4.005772777272388
n_U07_DN_2: [-2.60740781  1.50538516  2.64224442] 4.005772777272388


In [124]:
n_B07_UP=np.cross(v_B0Te1_up,v_B07)
n_B07_DN=np.cross(v_B07,v_B0Te6_dn)

m_n_B07_UP=np.linalg.norm(n_B07_UP)
m_n_B07_DN=np.linalg.norm(n_B07_DN)

n_B07_DN_2=np.cross(v_B0Te6_dn,v_B07)
m_n_B07_DN_2=np.linalg.norm(n_B07_DN_2)

print('n_B07_UP:',n_B07_UP,m_n_B07_UP)
print('n_B07_DN:',n_B07_DN,m_n_B07_DN)
print('n_B07_DN_2:',n_B07_DN_2,m_n_B07_DN_2)

n_B07_UP: [-2.5349195   1.46353364  2.6422824 ] 3.9432732420843597
n_B07_DN: [-2.60741308  1.50538773  2.64225293] 4.0057827892436455
n_B07_DN_2: [ 2.60741308 -1.50538773 -2.64225293] 4.0057827892436455
